- Dockerfile
- files/provision-user
- bump latest version of kops
- include helm 2.9.0
> helm and kops updates

- Dockerfile.centos7
- Dockerfile.debian
- files/provision-user
* Installed utils in both Dockerfiles: dep, gomplate, gitslave, cobra, crictl,
goling, gopm, govc, hub, mh, yq
* Set symlinks to default bin versions in both Dockerfiles: helm, kops
* Removed X libs from Dockerfile.centos7
* Set gopath for golang to /go
> Installed several missing utils from orig KDK

- files/provision-user
- kdk
* Enabled container priviliged mode through kdk config
* Added mounting of docker socket from host into image
* Added setting group ownership of docker sock to 'docker' group
* Added user to 'docker' group
> Enabled docker in docker

- README.md
see 6868e274e673f80ea1a48bf5a3bbfb16512bf01e
> Follow command change (ssh, up) in README.md

- Dockerfile.centos7
- Dockerfile.debian
- files/provision-user
- kdk
* Also, enables pure docker in docker.
> Enable systemd init system, Enable PURE Docker in Docker

- kdk
see 6868e274e673f80ea1a48bf5a3bbfb16512bf01e
> Fix "kdk restart" after command change

- Dockerfile.debian
- add powerline font package
- add locales package
- bump go version
- bump helm 2.9.x version
- bump default kubectl version to 1.10.5
- add v1.11.0 of kubectl
- add kubetail
- bump vim version
- replace tabs w/ whitespace in dockerfile
> Fix fonts and misc updates

- Dockerfile.debian
Added drone CLI v0.8.5 for Dockerized KDK
> Adding drone cli for kdk docker

- kdk
> Generate SSH key for current user instead of root

- Gopkg.lock
- cmd/destroy.go
- cmd/init.go
- cmd/provision.go
- cmd/prune.go
- cmd/pull.go
- cmd/restart.go
- cmd/root.go
- cmd/snapshot.go
- cmd/ssh.go
- cmd/up.go
- cmd/version.go
- files/provision-user
- implement up cmd
- quiet output of user provision
> Implement up command

- cmd/destroy.go
- cmd/init.go
- cmd/root.go
- cmd/snapshot.go
- cmd/ssh.go
- cmd/up.go
- cmd/version.go
- internal/app/kdk/destroy.go
- internal/app/kdk/init.go
- internal/app/kdk/provision.go
- internal/app/kdk/pull.go
- internal/app/kdk/snapshot.go
- internal/app/kdk/up.go
- internal/pkg/utils/misc.go
- internal/pkg/utils/ssh.go
- add config writing to init command
- more cleanup and reorg
- allow ability to run multiple KDK containers simultaneously
> Init command improvements

- Gopkg.lock
- README.md
- cmd/pull.go
- cmd/root.go
- cmd/ssh.go
- cmd/up.go
- internal/app/kdk/init.go
- internal/app/kdk/provision.go
- internal/app/kdk/pull.go
- internal/app/kdk/snapshot.go
- internal/app/kdk/up.go
* Uses yaml marshal/unmarshal to read/write configuration files.
> Refactored ~/.kdk/config.yaml file to use Docker lib structs

- Dockerfile.debian
- Gopkg.lock
- README.md
- cmd/init.go
- cmd/root.go
- cmd/ssh.go
- files/usr/local/bin/provision-user
- install
- internal/app/kdk/init.go
- internal/app/kdk/pull.go
- internal/app/kdk/up.go
Rebasing https://github.com/cisco-sso/kdk/pull/35
> Rebasing "Feature/windows support #35" on top of PR#36

- .gitignore
- .goreleaser.yml
- HACKING.md
Needs peer-testing to fully validate.
> Add .goreleaser.yml, HACKING.md with first pass at goreleaser how-to

- README.md
- files/usr/local/bin/provision-user
> Update READEME quickstart

- Gopkg.lock
- Makefile
- cmd/kdk/init.go
- cmd/kdk/kdk.go
- cmd/kdk/update.go
- files/Dockerfile
- main.go
- pkg/kdk/update.go
- pkg/kdk/version.go
- add update cmd
- update path to versioning
- update image-tag path
> Add update command

- .goreleaser.yml
- Makefile
- pkg/kdk/config.go
> goreleaser fixes

- Gopkg.lock
- README.md
- cmd/kdk/init.go
- pkg/kdk/config.go
- pkg/kdk/snapshot.go
- pkg/kdk/ssh.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
- automatically assign port
- remove need to specify port when running multiple KDKs
- update README
> Remove need for port parameter

- pkg/kdk/ssh.go
- pkg/kdk/up.go
fixes:
- https://github.com/cisco-sso/kdk/issues/50
> Fix issue where KDK up fails when previous KDK container has exited

- files/install
- pkg/kdk/update.go
- pkg/keybase/keybase.go
* Windows does not have a USER variable, but instead a USERNAME variable
> Fixed windows install script

- Gopkg.lock
- files/Dockerfile
* Reduced from 3.58GB to 2.91GB, a savings of 670MB
* Compiled minimal emacs from scratch to save 100MB
* Used multi-stage build to leave behind build libs and artifacts
```
DAVWANG4-M-1475:~ davwang4$ docker history ciscosso/kdk:test
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
a7c68500f854        9 minutes ago       /bin/sh -c #(nop)  CMD ["/lib/systemd/system…   0B
08d8077f44f1        9 minutes ago       /bin/sh -c #(nop)  EXPOSE 2022                  0B
bee2cf1eda2e        10 minutes ago      /bin/sh -c #(nop) COPY dir:77001fca8f2fe88de…   4.42kB
b4d3796b34a7        10 minutes ago      /bin/sh -c #(nop) COPY dir:13d1c6e513048810a…   150MB
114bfe9a9e3b        10 minutes ago      /bin/sh -c #(nop) COPY …
```
> Optimized docker image size via multi-stage builds

- files/Dockerfile
- split compilation steps in Dockerfile into discrete layers
> Add layers to Dockerfile

- pkg/kdk/pull.go
- pkg/kdk/update.go
* Prior would attempt to pull the existing image.
* Changed to pull the new version
> Fixed docker update pull race condition

- Makefile
- cmd/kdk/pull.go
- pkg/kdk/pull.go
- pkg/kdk/ssh.go
- pkg/kdk/update.go
Tested on linux, mac, windows (powershell).
I think linux support is good to go now.
> Re-enabled docker pull on kdk ssh if image not present

- Gopkg.lock
- Gopkg.toml
- cmd/kdk/init.go
- cmd/kdk/kdk.go
- cmd/kdk/pull.go
- cmd/kdk/version.go
- pkg/kdk/config.go
- pkg/kdk/destroy.go
- pkg/kdk/provision.go
- pkg/kdk/prune.go
- pkg/kdk/pull.go
- pkg/kdk/snapshot.go
- pkg/kdk/ssh.go
- pkg/kdk/up.go
- pkg/kdk/update.go
- pkg/keybase/keybase.go
One of many steps to get pretty docker pull output.
> Downcased Sirupsen -> sirupsen

- pkg/kdk/pull.go
Short term fix for #92 
Looks like:
```
$ ./_dist/darwin-amd64/kdk pull
WARN[0000] Upgrade Available
***************************************
Some KDK components are out of date
Latest Version:                      0.10.0
Binary Version:                      0.9.9-8-gf07d7e0-dirty
Config Version:                      0.9.9
Container Present at Config Version: false
Please upgrade the KDK with the commands:
sudo kdk update
kdk destroy
kdk ssh
***************************************
INFO[0000] Pulling KDK image. This may take a moment...
INFO[0000] Pulling missing KDK Image                     tag=0.9.9
{ID:0.9.9 Progress: ProgressDetail:{Current:0 Total:0} Status:Pulling from ciscosso/kdk}
{ID:05d1a5232b46 Progress: ProgressDetail:{Current:0 Total:0} Status:Already exists}
{ID:8c492d4826c6 …
```
> Print `kdk pull` status by default.

- cmd/kdk/kubesync.go
- pkg/kdk/config.go
- pkg/kdk/kubesync.go
> Add `kdk kubesync`

- pkg/kdk/config.go
- pkg/kdk/kubesync.go
- pkg/kdk/ssh.go
- This PR also causes `kdk kubesync` to auto start KDK.
> Add and implement cfg.Start()

- cmd/kdk/init.go
- cmd/kdk/kdk.go
- cmd/kdk/pull.go
- cmd/kdk/version.go
- pkg/kdk/destroy.go
- pkg/kdk/provision.go
- pkg/kdk/prune.go
- pkg/kdk/snapshot.go
- pkg/kdk/up.go
- pkg/kdk/update.go
- pkg/keybase/keybase.go
- fixes https://github.com/cisco-sso/kdk/issues/99
> Add option to restart stopped KDK container

- Makefile
- README.md
Made minor edits because people werent' seeing the detailed install instructions
> Doc updates

- files/Dockerfile
* Add go-task
* Add grpcurl
* Bump drone-cli version
* Bump golang version
* Bump goreleaser version
* Bump hugo version
* Bump jq version
* Bump kubectl versions
* Bump kubetail version
* Bump mc version
* Bump terraform version
> Tool additions and updates

- pkg/keybase/keybase.go
* Upgrades of Keybase installs later versions of Dokan, which moves the install
location of the mirror.exe binary depending on the version
"c:\Program Files\Dokan\Dokan Library-x.y.z"
Thus, the install path of mirror.exe changes
* Changed the mirror script to *search* for mirror.exe and use the first find.
> Fixed bug where kdk unable to locate mirror.exe on Windows

- files/Dockerfile
- files/provision.sh
- files/usr/local/bin/provision-user
- packer/Makefile
- packer/ubuntu-18.04.json
> Made Packer Vagrant Build Work!  On par with Docker Build

- files/provision.sh
- packer/packer_hyperv.json
- packer/packer_virtualbox.json
* Allows us to run provision script on regular ubuntu bionic machines
> Added ubuntu build target

- files/provision.sh
- quiet noisy build output
- update node to v13.x
> Fix MH installation

- files/provision.sh
* The quiet wrapper func seemed to be eating bad exit codes
* Quiet was also hiding fail output
* Removed quiet
* Fixed emacs install by fixing install of gnutls
> Disabled 'quiet', fixed emacs

- files/provision.sh
- packer/Makefile
- packer/README.md
- packer/Vagrantfile_hyperv.tmpl
- packer/packer_hyperv.json
> Updated packer scripts for ubuntu-20.04

- files/Dockerfile
- files/usr/local/bin/provision-user
* Removed masking of hostname, hosts, and resolv.conf mounts
* Also sorted systemctl mask args.
> Fixed DNS race condition for docker ubuntu-20.04

- files/provision.sh
Need `  -P, --prettyPrint   pretty print` to output better YAML.
> Update to yq (go version) to v3

- .travis.yml
- Makefile
- files/provision.sh
- packer/packer_hyperv.json
- packer/packer_virtualbox.json
* https://app.vagrantup.com/generic/boxes/ubuntu2004
> Switched virtualbox from bento image to 'generic' image

- files/provision.sh
- packer/README.md
- packer/Vagrantfile_hyperv.tmpl
* I've already uploaded the windows hyperv image to vagrant cloud.
> Fixed windows hyperv packer build to work with new Packer version

- files/provision.sh
Pin Terraform version to get a stable kdk env for deployment.
> Pin Terraform version

- files/provision.sh
> Install pre-commit python package

- files/provision.sh
etcd community changed release artifacts from tar.gz to tar.
> fix etcd installation
