- kdk
* Command fails if the container is already stopped
* kdk_container.remove(force=True) will remove the container
regardless of if it is running or stopped
> Fixed destroy command for already stopped kdk

- kdk
A lot of operating systems still default to Python 2.
i.e.
MacOS:
> $ python --version
> Python 2.7.15
Debian 9/Stretch
> $ python --version
> Python 2.7.13
> Explicitly use Python 3

- Dockerfile.debian
https://github.com/cisco-sso/ansible-role-k8s-devkit/pull/6#issuecomment-411224132
on debian based systems, we need to `source /etc/bash_completion` in `~/.bashrc` so will create a PR to the https://github.com/cisco-sso/yadm-dotfiles as well to have this enabled by default like in the rhel based vagrant kdk
ptal @dcwangmit01
> generate bash completion for kubectl and helm

- Makefile
- cmd/root.go
- main.go
* `go build` and `go install` will result in `kdk version`=="undefined"
* `make build build-cross` will result in `kdk version` being set
as: `<latest_tag_version>(-optional_num_commits)+<git-commit>(-optional_git_status)`
example: 0.7.0                   # where branch head equals the tag with no changes
example: 0.7.0-1+gdcd50f0        # where branch head is beyond last tag by 2 commits
example: 0.7.0-0+gb2842cd-dirty  # where branch head is beyond last tag by 1 commit
> Enable auto-versioning

- cmd/kdk/destroy.go
- cmd/kdk/init.go
- cmd/kdk/kdk.go
- cmd/kdk/provision.go
- cmd/kdk/prune.go
- cmd/kdk/pull.go
- cmd/kdk/snapshot.go
- cmd/kdk/ssh.go
- cmd/kdk/up.go
- cmd/kdk/update.go
- pkg/kdk/config.go
- pkg/kdk/destroy.go
- pkg/kdk/provision.go
- pkg/kdk/prune.go
- pkg/kdk/pull.go
- pkg/kdk/snapshot.go
- pkg/kdk/ssh.go
- pkg/kdk/up.go
- pkg/kdk/update.go
- fix update cmd
* Upon creation/re-creation of KDK container, check if the KDK image
and binary are the latest version.
- if not prompt user to update
* If the user wants to run with the current versions of the kdkbin/image
- they can the option `--skip-update` flag to continue using the
current binary and current image.
* The kdk update command will warn the user before doing anything that will;
- download and overwrite a new kdk binary
- pull the new kdk docker images
- overwrite the ./.kdk/<kdk-name>/config file
- fix debug flag
> Update cmd enhancements

- Makefile
- files/usr/local/bin/kdk-setup.sh
* Only happens on Docker for Windows machines with no
DNS search domain set
> Workaround a windows malformed /etc/resolv.conf issue

- pkg/kdk/kubesync.go
ref: https://github.com/cisco-sso/kdk/pull/94#discussion_r222006320
> Fix mistake: ~/.kubetest -> ~/.kube

- files/Dockerfile
- add helm 2.11.0 and set as default
- add kubectl 1.12.1 and set as default
- goreleaser arm64 → x86_64
- update golint go get url
- remove gitslave
- pin mc version
- version bumps
- easyrsa 3.0.4 → 3.0.5
- git 2.19.0 → 2.19.1
- go 1.11 → 1.11.1
- gomplate 2.8.0 → 3.0.0
- goreleaser 0.86.0 → 0.88.0
- hugo 0.48 → 0.49.2
- kubectl 1.10.6 → 1.10.9
- kubectl 1.11.2 → 1.11.3
- kubetail 1.6.1 → 1.6.4
- redis-cli tools 4.0.10 → 5.0.0
- vim 8.1.0290 → 8.1.04
- zsh 5.5.1 → 5.6.2
> Update tool versions

- files/Dockerfile
Version 1.0.0 is breaking the drone cli execution as it is not compatible with currently installed server version.
> [drone] Downgrading to version v0.8.6 as that the currently supported version

- files/Dockerfile
Thanks @dcwangmit01 ! I have now addressed the comments in https://github.com/cisco-sso/kdk/pull/107
I need to release it as drone CLI is broken in latest `KDK`
> [drone] making both the version 1.0.0 and 0.8.6 available and creating soft link to latest

- pkg/keybase/keybase.go
* When this script is run via:
powershell keybase-mirror.cmd start
* The script prior otherwise worked when run from the command line,
without the 'powershell' in front
> Removed SET vars which don't seem to take effect

- scripts/cicd.sh
* Current goreleaser install uses HEAD, which is broken right now
* Use the binary install of goreleaser
> Fix install of goreleaser

- files/Dockerfile
This PR removes old deprecated kops version and adds the latest stable version.
> Remove deprecated 1.9.2 kops and add 1.11.0

- files/Dockerfile
- Update direnv 2.17.0 -> 2.19.2
- Update drone-cli 1.0.0 -> 1.0.7
- Update easy-rsa 3.0.5 -> 3.0.6
- Update go-task 2.2.0 -> 2.4.0
- Update gomplate 3.0.0 -> 3.2.0
- Update golang 1.11.2 -> 1.12
- Update goreleaser 0.93.2 -> 0.101.0
- Update grpcurl 1.0.0 -> 1.1.0
- Update helm 2.11.0 -> 2.12.3
- Update hugo 0.51 -> 0.54.0
- Update kops 1.10.0 -> 1.10.1
- Update kubectl
- Update kubetail 1.6.5 -> 1.6.7
- Update mc (minio CLI)
- Update terraform 0.11.10 -> 0.11.11
- Pin pipenv version
- Update redis 5.0.0 -> 5.0.3
> Tool updates

- files/provision.sh
- packer/.gitignore
- packer/README.md
- packer/ubuntu-18.04.json
Worked for me. Once the image is built, imported and running, try executing `sudo cat /opt/test.txt`.
Would like help testing the new readme. I ran out of time today to do thorough re-test using my own writing.
> Add ability to build Vagrant images using Packer.

- files/provision.sh
- packer/ubuntu-18.04.json
This fix helps, but still hit:
```
vagrant: Get:29 http://archive.ubuntu.com/ubuntu bionic-backports/main i386 Packages [2,516 B]
vagrant: Get:30 http://archive.ubuntu.com/ubuntu bionic-backports/main Translation-en [1,644 B]
vagrant: Get:31 http://archive.ubuntu.com/ubuntu bionic-backports/universe i386 Packages [3,732 B]
vagrant: Get:32 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [3,728 B]
vagrant: Get:33 http://archive.ubuntu.com/ubuntu bionic-backports/universe Translation-en [1,696 B]
vagrant: Fetched 6,164 kB in 17s (364 kB/s)
vagrant: Reading package lists...
vagrant: Reading package lists...
vagrant: Building dependency tree...
vagrant: Reading state information...
==> vagrant: E: Unable to locate package libevent-2.0-5
==> vagrant: E: Couldn't find …
```
> Run provision script w/sudo in vagrant. Replace tabs with spaces.

- files/Dockerfile
- files/provision.sh
- files/usr/local/bin/provision-user
* Needed to do this because debian vagrant images don't
support hyper-v.
* Future vagrant images will need to run on both Mac
and Windows
> Switched Docker image to Ubuntu 18.04LTS Bionic

- files/provision.sh
Tried the vagrant image build locally:
```
vagrant@vagrant:~$ jsonnetfmt
ERROR: must give filename
Jsonnet reformatter v0.13.0
jsonnetfmt {<option>} { <filename> }
Note: Some options do not support multiple filenames
Available options:
-h / --help             This message
-e / --exec             Treat filename as code
-o / --output-file <file> Write to the output file rather than stdout
-i / --in-place         Update the Jsonnet file(s) in place.
--test                  Exit with failure if reformatting changed the file(s).
-n / --indent <n>       Number of spaces to indent by (default 2, 0 means no change)
--max-blank-lines <n>   Max vertical spacing, 0 means no change (default 2)
--string-style <d|s|l>  Enforce double, single (default) quotes or 'leave'
--comment-style <h|s|l> # (h), // …
```
> Install jsonnetfmt.

- files/provision.sh
- packer/Makefile
* Fixes a filesystem bug.  Vbox 6.0.10 is broken
Issue workaround of:
https://github.com/hashicorp/vagrant/issues/10913#issuecomment-513978619
This fixes the virtualbox filesystem problems.  Downgraded the kernel to latest 4.x series.  Downgraded vbox guest additions only from 6.0.10 -> 6.0.4 .  The build env was the latest 6.0.10, but the guest additions installed are 6.0.4.  Therefore, no need to pin to an older version of virtualbox for neither builders or normal users.  You can "vagrant box update" in ksng1 to get the latest, since it's already uploaded to vagrant cloud
> Downgrade vbox additions and kernel

- .travis.yml
- Makefile
- README.md
- files/Dockerfile
- files/provision.sh
- packer/Makefile
- packer/README.md
- packer/packer_hyperv.json
- packer/packer_virtualbox.json
* Require that the user provide a GITHUB_API_TOKEN that is
used upon calling the Github API to figure out latest releases.
* This fixes random CircleCI build failures, since non-auth'd
requests are counted by egress IP address.
* This also fixes local build failures.
* User now required to set env var GITHUB_API_TOKEN
> Fixed build failures from Github API Throttling Limits

- files/provision.sh
This version of jb will install jsonnet lib to go-like vendor directories which will help us a lot:
https://github.com/jsonnet-bundler/jsonnet-bundler/releases/tag/v0.3.0
> pre-install jb v0.3.0

- files/provision.sh
Pin pyYAML version to address:
> ERROR: awscli 1.18.3 has requirement PyYAML<5.3,>=3.10, but you'll have pyyaml 5.3 which is incompatible.
> ...
> ERROR: paramiko 2.7.1 has requirement cryptography>=2.5, but you'll have cryptography 2.1.4 which is incompatible.
run go get under /tmp to avoid:
```
changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git checkout -- <file>..." to discard changes in working directory)
modified:   go.mod
modified:   go.sum
```
> fix build failure

- README.md
Update document to provide workaround of ssh-agent lost sock problem (seems it happens to container kdk only), there should be a better way by changing https://github.com/cisco-sso/yadm-dotfiles/blob/master/.bash_profile#L19-L44 to limit the `else` part to vagrant only (if vagrant needs this behavior).
EDIT: do not need a release for this one.
> Update README for ssh-agent problem

- files/provision.sh
* easy-rsa modified their release package formats.
* grpcurl did not release the binary in their latest release.
Their version bumped only libraries.  Thus, pin to 1.5.0.
> Fixed code rotted dependencies

- Makefile
- files/Dockerfile
* Impact was minimal.  Token was scoped without access to any repos.  It was
scoped only for basic API queries for rate limiting.
* Old token, found in docker build history of prior images has been
invalidated
> Fixed docker build history secret leak of GITHUB_API_TOKEN

- files/provision.sh
- the high uid/gid of /usr/local/bin/etcdctl prevents image being run in
circleci because of userns issue
https://circleci.com/docs/2.0/high-uid-error/
> Fix etcdctl uid/gid

- files/usr/local/bin/provision-user
- If user mounts paths in a XDG path the mount permission can break
other tools that use XDG paths
> Fix permissions for XDG like paths

- files/provision.sh
Update jb to 0.4.0, note that install through `go get` no longer has the right version unless tweak flags (https://github.com/jsonnet-bundler/jsonnet-bundler/issues/117).
> Update to jb 0.4.0

- files/provision.sh
Switches to use the extracted cobra-cli command since it is being removed from the github.com/spf13/cobra module (xref https://github.com/spf13/cobra/issues/1597)
> Switch to standalone cobra-cli dependency
